### PR TITLE
library/pci_doe_responder_lib: Use libspdm DOE encode/decode helpers

### PR DESCRIPTION
**Pull request by alistair23**
Instead of encoding and decoding DOE discovery packets manually inside spdm-emu let's instead use the generic helper functions in libspdm. This way we can test functions that others can also utilise to when using libspdm.

### CODE REVIEW

**Comment by alistair23** [comment]
This depends on https://github.com/DMTF/libspdm/pull/2012 being merged and then the version of libspdm to be updated to include the change from https://github.com/DMTF/libspdm/pull/2012. It won't build until then

**Comment by jyao1** [comment]
> This depends on https://github.com/DMTF/libspdm/pull/2012 being merged and then the version of libspdm to be updated to include the change from https://github.com/DMTF/libspdm/pull/2012. It won't build until then

That is fine. Question: if you think this patch is ready for review?

**Comment by alistair23** [comment]
This is ready to go, it just needs https://github.com/DMTF/libspdm/pull/2012 merged first. Hence the draft status as it would break the build if merged without https://github.com/DMTF/libspdm/pull/2012

**Comment by jyao1** [comment]
> This is ready to go, it just needs https://github.com/DMTF/libspdm/pull/2012 merged first. 

OK. if so, please change to ready for review. I will sync libspdm, then merge this.

Draft means you are still working on it, IMHO.

> Hence the draft status as it would break the build if merged without https://github.com/DMTF/libspdm/pull/2012

I will not merge anything if CI fails.

**Review by jyao1 — APPROVED** [review]

**Pull request merged**
